# Generated by Django 3.2.7 on 2021-10-07 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('subheading1', models.CharField(blank=True, max_length=40, null=True)),
                ('para1', models.TextField(default='Paragraph 1')),
                ('subheading2', models.CharField(blank=True, max_length=40, null=True)),
                ('para2', models.TextField(blank=True, null=True)),
                ('subheading3', models.CharField(blank=True, max_length=40, null=True)),
                ('para3', models.TextField(blank=True, null=True)),
                ('subheading4', models.CharField(blank=True, max_length=40, null=True)),
                ('para4', models.TextField(default='Paragraph 4')),
                ('subheading5', models.CharField(blank=True, max_length=40, null=True)),
                ('para5', models.TextField(blank=True, null=True)),
                ('subheading6', models.CharField(blank=True, max_length=40, null=True)),
                ('para6', models.TextField(blank=True, null=True)),
                ('subheading7', models.CharField(blank=True, max_length=40, null=True)),
                ('para7', models.TextField(default='Paragraph 7')),
                ('subheading8', models.CharField(blank=True, max_length=40, null=True)),
                ('para8', models.TextField(blank=True, null=True)),
                ('subheading9', models.CharField(blank=True, max_length=40, null=True)),
                ('para9', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='')),
                ('image_caption1', models.CharField(blank=True, max_length=40, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_caption2', models.CharField(blank=True, max_length=40, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_caption3', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
