# Generated by Django 3.2.7 on 2021-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211001_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_caption1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_caption2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_caption3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
