# Generated by Django 3.2.7 on 2021-10-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211006_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clearance',
        ),
    ]
